"""
evaluator.py — RAGAS 0.4.x evaluation of the RAG pipeline

Loads the testset generated by scripts/generate_testset.py,
runs the RAG pipeline on each question, then scores with 4 RAGAS metrics:
  - faithfulness        (is the answer grounded in the retrieved context?)
  - answer_relevancy    (does the answer address the question?)
  - context_precision   (are retrieved chunks relevant to the question?)
  - context_recall      (does the context contain what's needed to answer?)

Run: python -m src.rag.evaluator
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

import pandas as pd
from langchain_groq import ChatGroq
from langchain_huggingface import HuggingFaceEmbeddings

from ragas import evaluate
from ragas.dataset_schema import EvaluationDataset, SingleTurnSample
from ragas.embeddings import LangchainEmbeddingsWrapper
from ragas.llms import LangchainLLMWrapper
from ragas.metrics.collections import (
    answer_relevancy,
    context_precision,
    context_recall,
    faithfulness,
)

from src.config import EMBEDDING_MODEL, GROQ_API_KEY, GROQ_MODEL, TESTSET_PATH, TOP_K
from src.rag.retriever import GeospatialRAG

log = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")


def run_evaluation(testset_path: Path = TESTSET_PATH) -> pd.DataFrame:
    """
    Run RAGAS 0.4.x evaluation over the pre-generated testset.

    Returns:
        DataFrame with per-question scores + aggregate metrics.
    """
    if not testset_path.exists():
        raise FileNotFoundError(
            f"Testset not found at {testset_path}.\n"
            "Run: python scripts/generate_testset.py"
        )

    # ── Load testset ──────────────────────────────────────────────────────────
    with open(testset_path) as f:
        records = json.load(f)

    if isinstance(records, dict):
        # Handle pandas orient="records" format saved as dict
        records = pd.read_json(testset_path).to_dict("records")

    log.info("Loaded %d QA pairs from testset", len(records))

    # ── Run RAG on each question ───────────────────────────────────────────────
    rag = GeospatialRAG()
    samples: list[SingleTurnSample] = []

    for i, item in enumerate(records):
        # Support both ragas 0.2.x and 0.4.x field names
        q = item.get("user_input") or item.get("question", "")
        gt = item.get("reference") or item.get("ground_truth", "")
        if not q:
            continue
        log.info("[%d/%d] Evaluating: %s", i + 1, len(records), q[:80])
        try:
            resp = rag.query(q, top_k=TOP_K)
            samples.append(
                SingleTurnSample(
                    user_input=q,
                    retrieved_contexts=resp.context_chunks,
                    response=resp.answer,
                    reference=gt,
                )
            )
        except Exception as e:
            log.warning("Skipping question %d due to error: %s", i, e)

    if not samples:
        raise RuntimeError("No valid samples to evaluate — check RAG pipeline.")

    # ── Build RAGAS EvaluationDataset ─────────────────────────────────────────
    dataset = EvaluationDataset(samples=samples)

    # ── Set LLM + embeddings on metrics ──────────────────────────────────────
    # RAGAS 0.4.x: metrics are module-level singletons; set LLM/embeddings on each.
    critic_llm = LangchainLLMWrapper(
        ChatGroq(api_key=GROQ_API_KEY, model=GROQ_MODEL, temperature=0)
    )
    critic_emb = LangchainEmbeddingsWrapper(
        HuggingFaceEmbeddings(model_name=EMBEDDING_MODEL)
    )

    metrics = [faithfulness, answer_relevancy, context_precision, context_recall]

    # Inject LLM into all metrics; embeddings only into answer_relevancy
    for m in metrics:
        m.llm = critic_llm
    answer_relevancy.embeddings = critic_emb

    # ── Evaluate ──────────────────────────────────────────────────────────────
    log.info("Running RAGAS evaluation on %d samples …", len(samples))
    result = evaluate(dataset=dataset, metrics=metrics)

    scores_df = result.to_pandas()
    metric_cols = [c for c in ["faithfulness", "answer_relevancy",
                                "context_precision", "context_recall"]
                   if c in scores_df.columns]

    summary = scores_df[metric_cols].mean()
    log.info("\n=== RAGAS Aggregate Scores ===\n%s", summary.to_string())

    return scores_df


if __name__ == "__main__":
    df = run_evaluation()
    out_path = TESTSET_PATH.parent / "eval_results.csv"
    df.to_csv(out_path, index=False)
    metric_cols = [c for c in ["faithfulness", "answer_relevancy",
                                "context_precision", "context_recall"]
                   if c in df.columns]
    print(f"\n✅ Evaluation complete. Results saved to {out_path}")
    print(df[metric_cols].mean().to_string())
